import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Loader2, CheckCircle2, XCircle, ShieldCheck, AlertTriangle, ArrowLeft } from 'lucide-react';

interface VerificationResult {
  valid: boolean;
  studentNumber?: string;
  studentName?: string;
  term?: string;
  academicYear?: string;
  average?: string;
  schoolName?: string;
  message?: string;
}

export default function VerifyReport() {
  const { hash } = useParams<{ hash: string }>();
  const [loading, setLoading] = useState(true);
  const [result, setResult] = useState<VerificationResult | null>(null);

  useEffect(() => {
    const verifyDocument = async () => {
      try {
        setLoading(true);
        // The hash is base64 encoded VERIFY:studentNumber:term:academicYear:average
        // We will decode it here to fetch the details. 
        // In a highly secure system, we would ping the backend to verify the exact record exists,
        // but for this implementation we will decode the string and do a basic structural validation.
        
        if (!hash) throw new Error("No verification code provided");
        
        const decoded = atob(hash);
        const parts = decoded.split(':');
        
        if (parts.length !== 5 || parts[0] !== 'VERIFY') {
          throw new Error("Invalid verification code structure");
        }
        
        const [_, studentNumber, term, academicYear, average] = parts;
        
        // Let's query the backend to actually verify this record exists and fetch the school and student name
        const response = await fetch(`/api/public/verify-report?studentNumber=${encodeURIComponent(studentNumber)}&term=${encodeURIComponent(term)}&academicYear=${encodeURIComponent(academicYear)}&average=${encodeURIComponent(average)}`);
        
        if (response.ok) {
          const data = await response.json();
          setResult({
            valid: true,
            studentNumber,
            studentName: data.studentName,
            schoolName: data.schoolName,
            term,
            academicYear,
            average
          });
        } else {
          setResult({
            valid: false,
            message: "This report card could not be found in the school's official records. It may be altered or invalid."
          });
        }
      } catch (error) {
        console.error("Verification failed:", error);
        setResult({
          valid: false,
          message: "The QR code is invalid, corrupted, or not generated by the MUCHI system."
        });
      } finally {
        setLoading(false);
      }
    };

    verifyDocument();
  }, [hash]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
        <Card className="w-full max-w-md shadow-lg">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Loader2 className="h-12 w-12 text-blue-600 animate-spin mb-4" />
            <h2 className="text-xl font-bold text-slate-900">Verifying Document...</h2>
            <p className="text-slate-500 text-center mt-2">Checking official school records</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md space-y-6">
        
        <div className="flex justify-center">
          <img src="/images/muchi-logo.png" alt="MUCHI Education Systems" className="h-12 opacity-80" onError={(e) => e.currentTarget.style.display = 'none'} />
        </div>

        <Card className="w-full shadow-xl border-t-4 overflow-hidden" style={{ borderTopColor: result?.valid ? '#22c55e' : '#ef4444' }}>
          <div className={`p-6 text-white text-center ${result?.valid ? 'bg-green-500' : 'bg-red-500'}`}>
            <div className="flex justify-center mb-4">
              {result?.valid ? (
                <div className="h-20 w-20 bg-white rounded-full flex items-center justify-center shadow-inner">
                  <ShieldCheck className="h-12 w-12 text-green-500" />
                </div>
              ) : (
                <div className="h-20 w-20 bg-white rounded-full flex items-center justify-center shadow-inner">
                  <XCircle className="h-12 w-12 text-red-500" />
                </div>
              )}
            </div>
            <h2 className="text-2xl font-black tracking-tight">
              {result?.valid ? "Official Document" : "Verification Failed"}
            </h2>
            <p className="text-white/90 font-medium mt-1">
              {result?.valid ? "This report card is valid and authentic." : "This document could not be authenticated."}
            </p>
          </div>

          <CardContent className="pt-6">
            {result?.valid ? (
              <div className="space-y-6">
                <div className="text-center pb-6 border-b border-slate-100">
                  <p className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-1">Issued By</p>
                  <h3 className="text-xl font-bold text-slate-900">{result.schoolName}</h3>
                  <p className="text-xs text-slate-400 mt-1 flex items-center justify-center gap-1">
                    <CheckCircle2 className="h-3 w-3 text-green-500" /> Powered by MUCHI Systems
                  </p>
                </div>

                <div className="space-y-4">
                  <div>
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Student</p>
                    <p className="text-lg font-bold text-slate-900">{result.studentName}</p>
                    <p className="text-sm text-slate-600 font-mono">{result.studentNumber}</p>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Academic Period</p>
                      <p className="text-sm font-bold text-slate-900">{result.term}</p>
                      <p className="text-xs text-slate-600">{result.academicYear}</p>
                    </div>
                    <div>
                      <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Overall Average</p>
                      <Badge variant="outline" className="text-lg py-1 px-3 bg-slate-50 border-slate-200">
                        {result.average}%
                      </Badge>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-center py-4 space-y-4">
                <AlertTriangle className="h-12 w-12 text-yellow-500 mx-auto opacity-50" />
                <p className="text-slate-600 leading-relaxed">
                  {result?.message}
                </p>
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 text-left text-sm text-slate-500">
                  <p className="font-bold text-slate-700 mb-2">Possible reasons:</p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>The QR code was not generated by our system</li>
                    <li>The grades have been altered on the printed copy</li>
                    <li>The student record has been deleted by the school</li>
                  </ul>
                </div>
              </div>
            )}
          </CardContent>
          
          <CardFooter className="bg-slate-50 border-t border-slate-100 p-4 flex justify-center">
            <Link to="/">
              <Button variant="ghost" size="sm" className="text-slate-500 hover:text-slate-700">
                <ArrowLeft className="h-4 w-4 mr-2" /> Go to MUCHI Homepage
              </Button>
            </Link>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}